Algoritmo "meu primeiro algoritmo"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/04/2020
Var
// Seção de Declarações das variáveis 
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota <- 100
   escreva ("resultado:", nota)

Fimalgoritmo