Algoritmo "Variaveis"
// Disciplina  :  [Algoritmos e Lógica de Programação]
// Professor   : Udemy Estia
// Autor(a)    : Jeanluiz
// Data atual  : 13/04/2020
Var
// Seção de Declarações das variáveis 
//primeiro nome
//segundo nome
//idade
//cidade
//endereço

    primeiroNome, segundoNome, cidade, endereco: caractere
    idade: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo